services:
  web:
    build:
      context: .
    container_name: any_folder
    image: any_folder
    volumes:
      - static_volume:/app/static
      - storage_volume:/app/storage
      - database_volume:/app/database
      - C:\AnythingTest:/app/AnythingLLM

    environment:
      - DJANGO_SETTINGS_MODULE=main.settings
      - PYTHONPATH=/app
      - DATABASE_DIR=/app/database
      - STORAGE_DIR=/app/storage
      - HOST_FOLDER=/app/AnythingLLM
      - PORT=8010


      # - IMAGE_DESCRIPTION_ACTIVATE=true
      # - OLLAMA_URL=http://localhost:11434/api/generate
      # - IMAGE_DESCRIPTION_MODEL=gemma3:12b
      # - IMAGE_DESCRIPTION_LANGUAGE=english
    ports:
      - "8010:8010"
    tty: true
    stdin_open: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static_volume:
  storage_volume:
  database_volume:
