services:
  web:
    build:
      context: .
    container_name: any_folder
    image: any_folder
    volumes:
      - static_volume:/app/static
      - storage_volume:/app/storage
      - database_volume:/app/database
      - C:\YOUR_PATH:/app/AnythingLLM
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings
      - PYTHONPATH=/app
      - DATABASE_DIR=/app/database
      - STORAGE_DIR=/app/storage
      - PORT=8010
      - ANYTHING_LLM_API=YOUR DEV API KEY  #You can find it here: AnythingLLM Settings -> Tools -> Developer API -> Generate New API Key
      - ANYTHING_LLM_URL=http://192.168.X.XX:8010   #This is your URL to your AnythingLLM Instance (can be desktop or docker version). Don't use localhost
      #You can get the URL using Developer API Window -> click on "Read the API documentation" -> URL could be http://192.168.80.40:3001/api/docs/ -> then use http://192.168.80.40:3001 with no "/" at the end

      - USE_CRON=true #if true, then it updates based on timings. If false, you can only update via post request to localhost:PORT/update_files/update/
      - CHECK_FILES_CRON=*/1 * * * *  # Run every minute, can be changed as needed
      #cron examples:
        # - `*/5 * * * *` (every 5 Minutes)
        # - `0 * * * *` (every hour)
        # - `0 */2 * * *` (every 2 hours)
        # - `0 9-17 * * 1-5` (every hour between 9-17 o clock, monday-friday)
    ports:
      - "8010:8010"
    tty: true
    stdin_open: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static_volume:
  storage_volume:
  database_volume:
