services:
  web:
    build:
      context: .
    container_name: any_folder
    image: any_folder
    volumes:
      - static_volume:/app/static
      - storage_volume:/app/storage
      - database_volume:/app/database
      - C:\MyFirstFolder:/app/AnythingLLM
      - C:\MySecondFolder:/app/AnythingLLM2
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings
      - PYTHONPATH=/app
      - DATABASE_DIR=/app/database
      - STORAGE_DIR=/app/storage
      - HOST_FOLDER=/app/AnythingLLM
      - PORT=8000
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    stdin_open: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static_volume:
  storage_volume:
  database_volume:
