services:
  web:
    build:
      context: .
    container_name: any_folder
    image: any_folder
    volumes:
      - static_volume:/app/static
      - storage_volume:/app/storage
      - database_volume:/app/database
      - C:\Users\Ron.Metzger\Documents\!!testing_files:/app/KornIntelligenz
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings
      - PYTHONPATH=/app
      - DATABASE_DIR=/app/database
      - STORAGE_DIR=/app/storage
      - PORT=8010
      - ANYTHING_LLM_API=YOUR-ANYTHINGLLM-DEV-API-KEY
      - ANYTHING_LLM_URL=YOUR-ANYTHINGLLM-URL
      - CHECK_FILES_CRON=*/1 * * * *  # Run every minute, can be changed as needed
        #cron examples:
      # - `*/5 * * * *` (every 5 Minutes)
      # - `0 * * * *` (every hour)
      # - `0 */2 * * *` (every 2 hours)
      # - `0 9-17 * * 1-5` (every hour between 9-17 o clock, monday-friday)
    ports:
      - "8010:8010"
    tty: true
    stdin_open: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static_volume:
  storage_volume:
  database_volume:
